Google Analytics Tracking
RagtagOpen/freefrom-map-frontend pull request #264
Opened 2021-05-03 15:50 UTC by egiurleo

Closes #119.

This PR adds the rest of Google Analytics tracking to the policy map. Here's an explanation of how all these actions get recorded:

Action | How it's referenced in GA
|-|-|
User clicked a state in the state list | Event with category `Click`, action `State list`, and the name of the state as the label
User clicked a state on the map | Event with category `Click`, action `Map`, and the name of the state as the label
User opened Glossary |  Modal view with `Glossary` as the name
User opened Scoring Guide |  Modal view with `Scoring Guide` as the name
User opened Methodology |  Page view with methodology URL
User opened Partner with FreeFrom form |  Page view with partner with FreeFrom URL
User submitted Partner with FreeFrom form |  Event with category `Form`, action `Submission`, and `partner-with-freefrom` as the label
User opened Build Collective Survivor Power form |  Page view with build collective survivor power URL
User submitted Build Collective Survivor Power form |  Event with category `Form`, action `Submission`, and `build-survivor-power` as the label
User opened Share Your Policy Ideas form |  Page view with share your policy ideas URL
User submitted Share Your Policy Ideas form |  Event with category `Form`, action `Submission`, and `share-your-policy-ideas` as the label
User opened Give Feedback form |  Page view with give feedback URL
User submitted Give Feedback form |  Event with category `Form`, action `Submission`, and `give-feedback` as the label
User opened Subscribe to State Updates form |  Modal view with `Sign Up for State Updates` as the name
User submitted Subscribe to State Updates form | Event with category `Form`, action `Submission`, and `subscribe-to-state-updates` as the label
User opened Report Missing/Outdated Information form | Modal view with `Report Missing Info` as the name
User submitted Report Missing/Outdated Information form | Event with category `Form`, action `Submission`, and `report-missing-info` as the label
User clicked "Share" button from homepage | Event with category `Click`, action `Share on Twitter` or `Share on Facebook`, and `homepage` as the label
User clicked "Share" button from state page | Event with category `Click`, action `Share on Twitter` or `Share on Facebook`, and `state page` as the label

2021-05-03 15:55 UTC, egiurleo commented on components/StatesList.js
> +                                    onLearnMoreClick={() => { trackEvent({ category: 'Click', action: 'State list', label: state.name}) }}
This gets passed down to the `Learn More` button in the state list and records a click on a specific state card in the list.

2021-05-03 15:55 UTC, egiurleo commented on components/Tracking.js
> +import { trackPageView } from 'utils';
I extracted this into a utility method so we could hypothetically reuse it if we needed it.

2021-05-03 15:55 UTC, egiurleo commented on components/UsMap.js
> +                trackEvent({category: 'Click', action: 'Map', label: name})
This records a click on a state in the map.

2021-05-03 15:55 UTC, egiurleo commented on components/common/ShareButtons.js
> +const ShareButtons = ({ className, context }) => (
We use the `context` prop to determine if this is being rendered on the home page or state page, and then use that to record a click on either of the buttons.

2021-05-03 15:55 UTC, egiurleo commented on components/common/StateUpdates.js
> +                        trackEvent({ category: 'Form', action: 'Submission', label: 'subscribe-state-updates'})
Record a submission of the "Subscribe to state updates" form.

2021-05-03 15:55 UTC, egiurleo commented on components/modal/Modal.js
> +                onClick={ () => { trackModal(title) } }
Track modal opening, including the title of the modal.

2021-05-03 15:55 UTC, egiurleo commented on pages/_app.js
> +        }
Initializing Google Analytics for use throughout the app.

2021-05-03 15:55 UTC, egiurleo commented on utils/forms.js
> +            trackEvent({ category: 'Form', action: 'Submission', label: path })
Track a form submission, including the name of the form we're submitting using the `path` argument.

2021-05-03 15:55 UTC, egiurleo commented on utils/tracking.js
> +    if(getCookiesFromLocalStorage && process.env.NEXT_PUBLIC_GA_ID) {
We only want to send info to GA if the user has agreed to cookies and we're in an environment with the `NEXT_PUBLIC_GA_ID` variable.

2021-05-06 03:48 UTC, sarahgreen requested changes
@egiurleo Hm, I don't think the specific events are populating in GA. This is what the 'real time' tab looks like after clicking around a bunch.
<img width="968" alt="Screen Shot 2021-05-05 at 8 46 05 PM" src="https://user-images.githubusercontent.com/6788487/117239080-f89a2d80-ade2-11eb-95b2-2eba0a27b392.png">

Worst case scenario, if we can't figure out how to pass through the events, we can still merge this in since we're capturing the number of overall visitors / active users.

2021-05-06 13:26 UTC, egiurleo commented
@sarahgreen this hasn't been deployed yet, right? So how could it be populating? (If I remember correctly our other change only started working once it was on staging, right?)

2021-05-06 15:18 UTC, sarahgreen commented
@egiurleo Ahh you're totally right. I got confused because of the active users showing up in GA, but that's because of the change we already merged into staging. Sorry! 😅

2021-05-06 15:18 UTC, sarahgreen approved these changes

2021-05-06 16:24 UTC, egiurleo commented
@sarahgreen All good :) Thanks for being proactive and making sure everything works.

2021-05-07 15:24 UTC, merged