Add take action links to state page (#92)
RagtagOpen/freefrom-map-frontend pull request #99
Opened 2021-02-22 00:24 UTC by landonreed

This PR:
- styles the Understanding Report links to match the mocks and
- adds the Take Action links

![image](https://user-images.githubusercontent.com/2370911/108643850-58d33180-747a-11eb-8fe4-de5f189040a3.png)

2021-02-22 01:25 UTC, sarahgreen requested changes

2021-02-22 01:25 UTC, sarahgreen commented on components/common/TakeAction.js
> +    {path: "/contact-your-legislators", label: "Contact Your Legislators"},
Looks like this page currently exists as `contact-legislators` not `contact-your-legislators`

2021-03-01 06:50 UTC, sarahgreen approved these changes
Looks great to me! @egiurleo any concerns or can we merge this in?

2021-03-01 16:36 UTC, egiurleo approved these changes
🎉 This looks great!

2021-03-01 18:25 UTC, merged